eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8282/eureka

spring:
  main:
#    allow-bean-definition-overriding: true
    web-application-type: none
  datasource:
    url: jdbc:postgresql://postgres:5001/netflix_oss
    username: postgres
    password: 147258369
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect